spring:
  application:
    name: streamify
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1
